costperfeval:
    pattern: "/costperfeval"
    legacy: "/perf_by_cost.php"
    controller: "alojaweb\\Controller\\CostPerfEvaluationController::costPerfEvaluationAction"
    screenName: "Cost Evaluation"

clustercosteffectiveness:
    pattern: "/clustercosteffectiveness"
    controller: "alojaweb\\Controller\\CostPerfEvaluationController::clusterCostEffectivenessAction"
    screenName: "Cost-Effectiveness of clusters"

costperfclustereval:
    pattern: "/costperfclustereval"
    controller: "alojaweb\\Controller\\CostPerfEvaluationController::costPerfClusterEvaluationAction"
    screenName: "Clusters Cost Evaluation"

bestcostperfclustereval:
    pattern: "/bestcostperfclustereval"
    controller: "alojaweb\\Controller\\CostPerfEvaluationController::BestCostPerfClusterEvaluationAction"
    screenName: "Best Clusters Cost Evaluation"

nodeseval:
    pattern: "/nodeseval"
    controller: "alojaweb\\Controller\\CostPerfEvaluationController::nodesEvaluationAction"
    screenName: "Number of Nodes Evaluation"

datasizeseval:
    pattern: "/datasizeseval"
    controller: "alojaweb\\Controller\\CostPerfEvaluationController::datasizesEvaluationAction"
    screenName: "Datasizes Scalability"

coreseval:
    pattern: "/coreseval"
    controller: "alojaweb\\Controller\\CostPerfEvaluationController::coresEvaluationAction"
    screenName: "Cores Scalability"

rameval:
    pattern: "/rameval"
    controller: "alojaweb\\Controller\\CostPerfEvaluationController::RAMEvaluationAction"
    screenName: "RAM Scalability"