index:
    pattern: "/"
    controller: "alojaweb\\Controller\\DefaultController::indexAction"

configimprovement:
    pattern: "/configimprovement"
    legacy: "/config_improvement.php"
    controller: "alojaweb\\Controller\\DefaultController::configImprovementAction"

benchexecutions:
    pattern: "/benchexecs"
    legacy: "/datatable.php"
    controller: "alojaweb\\Controller\\DefaultController::benchExecutionsAction"

benchdata:
    pattern: "/benchdata"
    controller: "alojaweb\\Controller\\RestController::benchExecutionsDataAction"

costperfeval:
    pattern: "/costperfeval"
    legacy: "/perf_by_cost.php"
    controller: "alojaweb\\Controller\\DefaultController::costPerfEvaluationAction"

perfcharts:
    pattern: "/perfcharts"
    legacy: "/charts1.php"
    controller: "alojaweb\\Controller\\DefaultController::performanceChartsAction"

counters:
    pattern: "/counters"
    legacy: "/counters.php"
    controller: "alojaweb\\Controller\\DefaultController::countersAction"

countersdata:
    pattern: "/countersdata"
    controller: "alojaweb\\Controller\\RestController::countersDataAction"

export2prv:
    pattern: "/export2prv"
    controller: "alojaweb\\Controller\\RestController::export2prvAction"
    
metrics:
    pattern: "/metrics"
    controller: "alojaweb\\Controller\\DefaultController::performanceTableAction"
    
metricsdata:
    pattern: "/metricsdata"
    controller: "alojaweb\\Controller\\RestController::metricsDataAction"
    
histogram:
    pattern: "/histogram"
    controller: "alojaweb\\Controller\\DefaultController::histogramAction"
    
histogramdata:
    pattern: "/histogramdata"
    controller: "alojaweb\\Controller\\RestController::histogramDataAction"

histogramtasksdata:
    pattern: "/histogramtasksdata"
    controller: "alojaweb\\Controller\\RestController::histogramTasksDataAction"

bestconfig:
    pattern: "/bestconfig"
    controller: "alojaweb\\Controller\\DefaultController::bestConfigAction"
    
bestconfigdata:
    pattern: "/bestconfigdata"
    controller: "alojaweb\\Controller\\DefaultController::bestConfigDataAction"
    
parameval:
    pattern: "/parameval"
    controller: "alojaweb\\Controller\\DefaultController::paramEvaluationAction"
    
publications:
    pattern: "/publications"
    controller: "alojaweb\\Controller\\DefaultController::publicationsAction"
    
team:
    pattern: "/team"
    controller: "alojaweb\\Controller\\DefaultController::teamAction"
    
clusters:
    pattern: "/clusters"
    controller: "alojaweb\\Controller\\DefaultController::clustersAction"
    
clustercosts:
    pattern: "/clustercosts"
    controller: "alojaweb\\Controller\\DefaultController::clusterCostsAction"

dbscan:
    pattern: "/dbscan"
    controller: "alojaweb\\Controller\\DefaultController::dbscanAction"

dbscandata:
    pattern: "/dbscandata"
    controller: "alojaweb\\Controller\\RestController::dbscanDataAction"

dbscanexecs:
    pattern: "/dbscanexecs"
    controller: "alojaweb\\Controller\\DefaultController::dbscanexecsAction"

dbscanexecsdata:
    pattern: "/dbscanexecsdata"
    controller: "alojaweb\\Controller\\RestController::dbscanexecsDataAction"

hdp2counters:
    pattern: "/hdp2counters"
    controller: "alojaweb\\Controller\\DefaultController::hdp2CountersAction"
    
hdp2countersdata:
    pattern: "/hdpcountersdata"
    controller: "alojaweb\\Controller\\RestController::hdp2countersDataAction"
   
histogramhdi:
    pattern: "/histogramhdi"
    controller: "alojaweb\\Controller\\DefaultController::histogramHDIAction"
     
histogramhdidata:
    pattern: "/histogramhdidata"
    controller: "alojaweb\\Controller\\RestController::histogramHDIDataAction"
    
histogramhditasksdata:
    pattern: "/histogramhditasksdata"
    controller: "alojaweb\\Controller\\RestController::histogramHDITasksDataAction"
    
clustercosteffectiveness:
    pattern: "/clustercosteffectiveness"
    controller: "alojaweb\\Controller\\DefaultController::clusterCostEffectivenessAction"
    
costperfclustereval:
    pattern: "/costperfclustereval"
    controller: "alojaweb\\Controller\\DefaultController::costPerfClusterEvaluationAction"
    
bestcostperfclustereval:
    pattern: "/bestcostperfclustereval"
    controller: "alojaweb\\Controller\\DefaultController::BestCostPerfClusterEvaluationAction"
